#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ ca_certs_secret_name = "flux-ca-certs"

#@ if data.values.ca_cert_data:

---
apiVersion: v1
kind: Secret
metadata:
  name: #@ ca_certs_secret_name
  namespace: flux-system
stringData:
  #@yaml/text-templated-strings
  ca.crt: |
    (@= data.values.ca_cert_data @)

#@overlay/match by=overlay.subset({"kind":"Deployment"}), expects="1+"
---
spec:
  template:
    spec:
      containers:
        #@overlay/match by="name"
        - name: manager
          #@overlay/match missing_ok=True
          volumeMounts:
            - name: ca-certs
              mountPath: /etc/ssl/certs/ca.crt
              readOnly: true
              subPath: ca.crt
      #@overlay/match missing_ok=True
      volumes:
        - name: ca-certs
          secret:
            secretName: #@ ca_certs_secret_name
#@ end
